apiVersion: v2
name: user-profile
description: user-profile service (ALP).
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: alp-service
    version: 0.1.0
    repository: "file://../alp-service"
