"""CBSE Class 8 — full-syllabus MCQ seed bank.

Covers every NCERT Class 8 chapter NOT already present in the
``cbse_polymorphic`` seed (which ships Force/Pressure, Light, Cell,
Rational Numbers, Linear Equations, Mensuration). Five PUBLISHED
MCQ_SINGLE questions per topic.

Tuple shape: ``(stem, [choice_a, choice_b, choice_c, choice_d],
correct_idx, difficulty_b)``. ``correct_idx`` is 0-based; ``difficulty_b``
is the IRT b-parameter on the conventional [-3, +3] scale (negative ⇒
easy, positive ⇒ hard).

Topic codes match the catalog migration ``019_seed_cbse_full_syllabus``.
The mapping ``TOPIC_IDS`` here is a code→UUID lookup for downstream
seed migrations.
"""

from __future__ import annotations

# (code, uuid) — must match alembic/catalog/versions/019_seed_cbse_full_syllabus.py
TOPIC_IDS: dict[str, str] = {
    # Class 8 Maths
    "C8M_QUAD":   "33333333-0000-0000-0000-000000000037",
    "C8M_PGEOM":  "33333333-0000-0000-0000-000000000038",
    "C8M_DATA":   "33333333-0000-0000-0000-000000000039",
    "C8M_SQ":     "33333333-0000-0000-0000-000000000040",
    "C8M_CUBE":   "33333333-0000-0000-0000-000000000041",
    "C8M_CQ":     "33333333-0000-0000-0000-000000000042",
    "C8M_AEI":    "33333333-0000-0000-0000-000000000043",
    "C8M_SOLID":  "33333333-0000-0000-0000-000000000044",
    "C8M_EXP":    "33333333-0000-0000-0000-000000000045",
    "C8M_DIP":    "33333333-0000-0000-0000-000000000046",
    "C8M_FACT":   "33333333-0000-0000-0000-000000000047",
    "C8M_GRAPH":  "33333333-0000-0000-0000-000000000048",
    "C8M_PWN":    "33333333-0000-0000-0000-000000000049",
    # Class 8 Science
    "C8S_CROP":   "33333333-0000-0000-0000-000000000050",
    "C8S_MICRO":  "33333333-0000-0000-0000-000000000051",
    "C8S_MATM":   "33333333-0000-0000-0000-000000000052",
    "C8S_COAL":   "33333333-0000-0000-0000-000000000053",
    "C8S_COMB":   "33333333-0000-0000-0000-000000000054",
    "C8S_CONS":   "33333333-0000-0000-0000-000000000055",
    "C8S_REPRO":  "33333333-0000-0000-0000-000000000056",
    "C8S_ADOL":   "33333333-0000-0000-0000-000000000057",
    "C8S_FRIC":   "33333333-0000-0000-0000-000000000058",
    "C8S_SOUND":  "33333333-0000-0000-0000-000000000059",
    "C8S_CEEC":   "33333333-0000-0000-0000-000000000060",
    "C8S_NAT":    "33333333-0000-0000-0000-000000000061",
    "C8S_STAR":   "33333333-0000-0000-0000-000000000062",
    "C8S_POLL":   "33333333-0000-0000-0000-000000000063",
    "C8S_SYN":    "33333333-0000-0000-0000-000000000064",
    # Class 8 Social Science
    "C8H_INTRO":  "33333333-0000-0000-0000-000000000065",
    "C8H_TRADE":  "33333333-0000-0000-0000-000000000066",
    "C8H_RULING": "33333333-0000-0000-0000-000000000067",
    "C8H_TRIBAL": "33333333-0000-0000-0000-000000000068",
    "C8H_REBEL":  "33333333-0000-0000-0000-000000000069",
    "C8H_NATL":   "33333333-0000-0000-0000-000000000070",
    "C8G_RES":    "33333333-0000-0000-0000-000000000071",
    "C8G_LSWVW":  "33333333-0000-0000-0000-000000000072",
    "C8G_MIN":    "33333333-0000-0000-0000-000000000073",
    "C8G_AGRI":   "33333333-0000-0000-0000-000000000074",
    "C8G_IND":    "33333333-0000-0000-0000-000000000075",
    "C8G_HUM":    "33333333-0000-0000-0000-000000000076",
    "C8C_CONST":  "33333333-0000-0000-0000-000000000077",
    "C8C_PARL":   "33333333-0000-0000-0000-000000000078",
    "C8C_JUDIC":  "33333333-0000-0000-0000-000000000079",
    "C8C_MARG":   "33333333-0000-0000-0000-000000000080",
    "C8C_PUB":    "33333333-0000-0000-0000-000000000081",
    "C8C_LAW":    "33333333-0000-0000-0000-000000000082",
    # Class 8 English
    "C8E_HONEY":  "33333333-0000-0000-0000-000000000083",
    "C8E_POEM":   "33333333-0000-0000-0000-000000000084",
    "C8E_ISH":    "33333333-0000-0000-0000-000000000085",
    "C8E_GRAM":   "33333333-0000-0000-0000-000000000086",
    "C8E_READ":   "33333333-0000-0000-0000-000000000087",
}


# Tuple shape: (stem, choices, correct_idx, difficulty_b)
TOPIC_QUESTIONS: dict[str, list[tuple[str, list[str], int, float]]] = {
    # ====================================================================
    # CLASS 8 — MATHEMATICS
    # ====================================================================
    "C8M_QUAD": [
        ("Which of the following is NOT a quadrilateral?",
         ["Trapezium", "Parallelogram", "Pentagon", "Rhombus"], 2, -1.0),
        ("Sum of interior angles of a quadrilateral is:",
         ["180°", "270°", "360°", "540°"], 2, -0.5),
        ("In a parallelogram, opposite sides are:",
         ["Equal and parallel", "Perpendicular", "Equal but not parallel", "Unequal"], 0, 0.0),
        ("A quadrilateral with exactly one pair of parallel sides is called:",
         ["Square", "Rhombus", "Trapezium", "Rectangle"], 2, 0.5),
        ("If three angles of a quadrilateral are 80°, 100°, 120°, the fourth is:",
         ["50°", "60°", "70°", "80°"], 1, 1.0),
    ],
    "C8M_PGEOM": [
        ("Minimum measurements needed to construct a unique quadrilateral:",
         ["3", "4", "5", "6"], 2, 0.0),
        ("To construct a parallelogram, we need to know:",
         ["Two adjacent sides only", "Two adjacent sides and one angle", "One side only", "All four angles"],
         1, 0.5),
        ("Which instrument is used to draw a perpendicular line accurately?",
         ["Protractor", "Set-square", "Compass", "Divider"], 1, -0.5),
        ("A square can be constructed when its ____ is known.",
         ["Side", "Perimeter only", "Diagonal only", "Either side or diagonal"], 3, 1.0),
        ("Constructing a rhombus requires:",
         ["One side only", "Both diagonals", "All angles", "Only the area"], 1, 0.5),
    ],
    "C8M_DATA": [
        ("Frequency of an observation means:",
         ["Total observations", "How many times it occurs", "Half the total", "Sum of values"], 1, -1.0),
        ("In a histogram, bars are drawn:",
         ["With gaps", "Without gaps for continuous data", "Only horizontally", "With dots"], 1, 0.0),
        ("A pie chart's complete circle represents:",
         ["360° = 100% of data", "180°", "100°", "any angle"], 0, -0.5),
        ("If probability of an event is 0, then the event is:",
         ["Certain", "Likely", "Impossible", "Equally likely"], 2, 0.5),
        ("Probability of getting a tail when a fair coin is tossed is:",
         ["0", "0.25", "0.5", "1"], 2, -0.5),
    ],
    "C8M_SQ": [
        ("The square of 13 is:",
         ["139", "169", "159", "189"], 1, -0.5),
        ("Square root of 144 is:",
         ["10", "11", "12", "13"], 2, -1.0),
        ("Which of the following is a Pythagorean triplet?",
         ["(2,3,4)", "(3,4,5)", "(4,5,6)", "(5,6,7)"], 1, 0.0),
        ("The number of digits in √10000 is:",
         ["1", "2", "3", "4"], 2, 0.5),
        ("Which of these is a perfect square?",
         ["50", "72", "121", "200"], 2, 0.0),
    ],
    "C8M_CUBE": [
        ("The cube of 4 is:",
         ["12", "16", "32", "64"], 3, -1.0),
        ("Cube root of 27 is:",
         ["2", "3", "4", "5"], 1, -1.0),
        ("Which of the following is a perfect cube?",
         ["100", "125", "150", "180"], 1, 0.0),
        ("Cube root of 1000 is:",
         ["10", "100", "20", "5"], 0, -0.5),
        ("The smallest number by which 392 should be multiplied to make it a perfect cube is:",
         ["3", "5", "7", "11"], 2, 1.0),
    ],
    "C8M_CQ": [
        ("If the cost price is ₹500 and selling price is ₹600, the profit % is:",
         ["10%", "16.67%", "20%", "25%"], 2, 0.0),
        ("Compound interest on ₹1000 at 10% p.a. for 2 years is:",
         ["₹200", "₹210", "₹220", "₹250"], 1, 0.5),
        ("Discount is calculated on:",
         ["Cost price", "Selling price", "Marked price", "Profit"], 2, -0.5),
        ("If 20% of a number is 50, the number is:",
         ["100", "150", "200", "250"], 3, 0.0),
        ("Simple interest on ₹2000 at 5% p.a. for 3 years is:",
         ["₹200", "₹250", "₹300", "₹350"], 2, -0.5),
    ],
    "C8M_AEI": [
        ("(a + b)² is equal to:",
         ["a² − 2ab + b²", "a² + 2ab + b²", "a² + b²", "a² − b²"], 1, -0.5),
        ("(x + y)(x − y) equals:",
         ["x² + y²", "x² − y²", "(x + y)²", "(x − y)²"], 1, 0.0),
        ("Product of monomials 3x and 4xy is:",
         ["7xy", "12x²y", "12xy", "12x²"], 1, -0.5),
        ("Coefficient of x in 5x − 3 is:",
         ["−3", "5", "5x", "x"], 1, -1.0),
        ("(2a − 3b)(2a + 3b) equals:",
         ["4a² + 9b²", "4a² − 9b²", "4a² + 6ab − 9b²", "2a − 3b"], 1, 0.5),
    ],
    "C8M_SOLID": [
        ("Number of faces of a cuboid is:",
         ["4", "6", "8", "12"], 1, -1.0),
        ("Euler's formula for polyhedra states:",
         ["V − E + F = 2", "V + E − F = 2", "V + E + F = 0", "V × E = F"], 0, 0.5),
        ("A cylinder has how many flat faces?",
         ["0", "1", "2", "3"], 2, -0.5),
        ("Number of vertices in a triangular prism:",
         ["3", "5", "6", "8"], 2, 0.0),
        ("A polyhedron all of whose faces are regular polygons is called:",
         ["Prism", "Pyramid", "Regular polyhedron", "Sphere"], 2, 1.0),
    ],
    "C8M_EXP": [
        ("Value of 2⁻³ is:",
         ["−8", "8", "1/8", "1/6"], 2, 0.0),
        ("Value of (5⁰) is:",
         ["0", "1", "5", "Undefined"], 1, -1.0),
        ("3⁴ × 3² equals:",
         ["3⁶", "3⁸", "9⁶", "27⁴"], 0, -0.5),
        ("Scientific notation of 5,90,000 is:",
         ["5.9 × 10⁴", "5.9 × 10⁵", "59 × 10⁴", "0.59 × 10⁶"], 1, 0.5),
        ("(2³)² is equal to:",
         ["32", "64", "128", "256"], 1, 0.0),
    ],
    "C8M_DIP": [
        ("If two quantities vary directly, their ratio is:",
         ["Variable", "Always 1", "Constant", "Inversely proportional"], 2, 0.0),
        ("A car covers 60 km in 1 hr. Distance in 4 hrs at the same speed:",
         ["120 km", "180 km", "240 km", "300 km"], 2, -0.5),
        ("If 5 workers complete a job in 12 days, 10 workers will take (inverse proportion):",
         ["6 days", "12 days", "18 days", "24 days"], 0, 0.5),
        ("Which is an example of inverse proportion?",
         ["Distance vs time at constant speed", "Number of workers vs days to finish a job", "Side length vs perimeter of a square", "Cost vs quantity at fixed price"],
         1, 0.0),
        ("If 3 books cost ₹150, 8 books cost:",
         ["₹250", "₹300", "₹400", "₹450"], 2, -0.5),
    ],
    "C8M_FACT": [
        ("Factor of 4x² − 9 is:",
         ["(2x − 3)(2x + 3)", "(2x − 3)²", "(4x − 3)(x + 3)", "(2x − 9)(2x + 1)"], 0, 0.5),
        ("Common factor of 6x² and 9x is:",
         ["3x", "6x", "9x", "x²"], 0, -0.5),
        ("x² + 5x + 6 factorises into:",
         ["(x + 2)(x + 3)", "(x − 2)(x − 3)", "(x + 1)(x + 6)", "(x + 6)(x − 1)"], 0, 0.0),
        ("Factor of x² − 25 is:",
         ["(x − 5)²", "(x + 5)²", "(x − 5)(x + 5)", "Cannot be factorised"], 2, -0.5),
        ("Result of 6x²y ÷ 2xy is:",
         ["3xy", "3x", "3y", "x²"], 1, 0.0),
    ],
    "C8M_GRAPH": [
        ("Which graph best shows the relationship between two continuous variables?",
         ["Bar graph", "Pie chart", "Histogram", "Line graph"], 3, 0.0),
        ("Coordinates of the origin in a Cartesian plane are:",
         ["(1,1)", "(0,0)", "(0,1)", "(1,0)"], 1, -1.0),
        ("If a point lies on the x-axis, its y-coordinate is:",
         ["1", "0", "Undefined", "Negative"], 1, -0.5),
        ("Graph of y = x is a:",
         ["Curve", "Circle", "Straight line through origin", "Parabola"], 2, 0.5),
        ("In a pie chart of 360°, a sector of 90° represents what fraction?",
         ["1/2", "1/3", "1/4", "1/6"], 2, -0.5),
    ],
    "C8M_PWN": [
        ("A number divisible by 3 has the sum of its digits divisible by:",
         ["2", "3", "5", "9"], 1, -0.5),
        ("Smallest 4-digit number divisible by 5 is:",
         ["1000", "1005", "1010", "1050"], 0, 0.0),
        ("Test of divisibility by 9: digit sum is divisible by:",
         ["3", "6", "9", "11"], 2, -0.5),
        ("If AB + BA = 99, the value of (A + B) is:",
         ["8", "9", "10", "11"], 1, 1.0),
        ("Numbers like 11, 22, 33 are divisible by:",
         ["7", "11", "13", "17"], 1, 0.0),
    ],

    # ====================================================================
    # CLASS 8 — SCIENCE
    # ====================================================================
    "C8S_CROP": [
        ("Crops grown in the rainy season are called:",
         ["Rabi", "Kharif", "Zaid", "Annual"], 1, -0.5),
        ("Wheat is mainly a:",
         ["Kharif crop", "Rabi crop", "Zaid crop", "Cash crop"], 1, -0.5),
        ("Process of loosening and turning the soil is called:",
         ["Sowing", "Tilling/ploughing", "Threshing", "Winnowing"], 1, -1.0),
        ("Storing food grains in the open should be avoided because of:",
         ["Sunlight", "Wind", "Pests and moisture", "Cold"], 2, 0.0),
        ("The use of chemical fertilisers in excess can cause:",
         ["Soil enrichment only", "Pollution of soil and water", "Higher yields permanently", "No effect"], 1, 0.5),
    ],
    "C8S_MICRO": [
        ("Which microorganism is used in making curd?",
         ["Yeast", "Lactobacillus", "Penicillium", "E. coli"], 1, -0.5),
        ("Which disease is caused by a virus?",
         ["Tuberculosis", "Typhoid", "Common cold", "Cholera"], 2, 0.0),
        ("Yeast is used in baking because it produces:",
         ["Oxygen", "Hydrogen", "Carbon dioxide", "Methane"], 2, -0.5),
        ("Penicillin is an example of:",
         ["Vaccine", "Antibiotic", "Antiseptic", "Vitamin"], 1, 0.5),
        ("Pasteurisation of milk is named after:",
         ["Edward Jenner", "Louis Pasteur", "Robert Koch", "Alexander Fleming"], 1, 0.0),
    ],
    "C8S_MATM": [
        ("Which of the following is a metal?",
         ["Carbon", "Sulphur", "Iron", "Oxygen"], 2, -1.0),
        ("Non-metals are generally:",
         ["Lustrous", "Malleable", "Poor conductors", "Ductile"], 2, -0.5),
        ("The most reactive metal among these is:",
         ["Iron", "Copper", "Sodium", "Gold"], 2, 0.0),
        ("Acid + metal usually gives a salt and:",
         ["Oxygen", "Hydrogen", "Carbon dioxide", "Water"], 1, -0.5),
        ("Which non-metal is required for combustion?",
         ["Nitrogen", "Argon", "Oxygen", "Helium"], 2, -0.5),
    ],
    "C8S_COAL": [
        ("Coal, petroleum and natural gas are called:",
         ["Renewable fuels", "Fossil fuels", "Bio-fuels", "Nuclear fuels"], 1, -1.0),
        ("Coke is obtained by:",
         ["Burning coal directly", "Heating coal in absence of air", "Mixing coal with water", "Electrolysis"], 1, 0.5),
        ("Petroleum is also known as:",
         ["Black gold", "Yellow gold", "White gold", "Blue gold"], 0, 0.0),
        ("LPG primarily contains:",
         ["Methane", "Butane and propane", "Ethanol", "Hydrogen"], 1, 0.0),
        ("Fossil fuels are exhaustible because:",
         ["They are unlimited", "Their formation takes millions of years", "They regrow yearly", "Sun makes them daily"], 1, -0.5),
    ],
    "C8S_COMB": [
        ("Substances that burn easily are called:",
         ["Combustible", "Non-combustible", "Inert", "Resistant"], 0, -1.0),
        ("Lowest temperature at which a substance catches fire is its:",
         ["Boiling point", "Ignition temperature", "Melting point", "Latent heat"], 1, 0.5),
        ("The hottest zone of a candle flame is:",
         ["Innermost dark zone", "Middle yellow zone", "Outer non-luminous zone", "Wick"], 2, 0.0),
        ("Fire extinguishers commonly use:",
         ["Hydrogen", "Carbon dioxide", "Oxygen", "Chlorine"], 1, -0.5),
        ("Calorific value is measured in:",
         ["Watts", "Joules per kilogram (J/kg) or kJ/kg", "Pascals", "Kelvin"], 1, 0.5),
    ],
    "C8S_CONS": [
        ("A protected area where wild animals are kept safe is a:",
         ["Zoo", "National park / sanctuary", "Botanical garden", "Aquarium"], 1, -0.5),
        ("Species found only in a particular region are called:",
         ["Migratory", "Endemic", "Endangered", "Extinct"], 1, 0.5),
        ("Project Tiger was launched in:",
         ["1947", "1973", "1985", "2000"], 1, 0.5),
        ("Cutting down of trees on a large scale is called:",
         ["Afforestation", "Deforestation", "Reforestation", "Conservation"], 1, -0.5),
        ("Red Data Book contains information about:",
         ["All animals", "Endangered species", "Domestic animals only", "Plants only"], 1, 0.0),
    ],
    "C8S_REPRO": [
        ("Fusion of male and female gametes is called:",
         ["Pollination", "Fertilisation", "Germination", "Budding"], 1, -0.5),
        ("Reproduction without fusion of gametes is called:",
         ["Sexual", "Asexual", "Vegetative only", "Cross"], 1, 0.0),
        ("Internal fertilisation is seen in:",
         ["Frog", "Fish", "Human", "Hydra"], 2, 0.0),
        ("Animals that lay eggs are called:",
         ["Viviparous", "Oviparous", "Hermaphrodite", "Marsupial"], 1, -0.5),
        ("Hydra reproduces by:",
         ["Binary fission", "Budding", "Spore formation", "Internal fertilisation"], 1, 0.5),
    ],
    "C8S_ADOL": [
        ("The period of life that begins with puberty is called:",
         ["Childhood", "Adolescence", "Old age", "Infancy"], 1, -1.0),
        ("Hormone produced by the testes is:",
         ["Insulin", "Thyroxine", "Testosterone", "Adrenaline"], 2, 0.0),
        ("Female hormone responsible for menstruation is:",
         ["Testosterone", "Oestrogen", "Insulin", "Glucagon"], 1, 0.5),
        ("The endocrine gland called the master gland is:",
         ["Thyroid", "Pituitary", "Pancreas", "Adrenal"], 1, 0.5),
        ("Sex of a human child is determined by:",
         ["Mother's chromosomes", "Father's chromosomes", "Diet", "Environment"], 1, 0.0),
    ],
    "C8S_FRIC": [
        ("Friction always:",
         ["Aids motion", "Opposes relative motion", "Has no direction", "Increases speed"], 1, -1.0),
        ("Which type of friction is the smallest?",
         ["Static", "Sliding", "Rolling", "Fluid"], 2, 0.5),
        ("Friction can be reduced by using:",
         ["Sand", "Lubricants", "Mud", "Glue"], 1, -0.5),
        ("Friction depends on:",
         ["Mass only", "Area only", "Nature of surfaces", "Colour"], 2, 0.0),
        ("Drag is the friction exerted by:",
         ["Solids", "Fluids (gases or liquids)", "Mirrors", "Magnets"], 1, 0.0),
    ],
    "C8S_SOUND": [
        ("Sound is produced by:",
         ["Reflection", "Vibration", "Magnetism", "Heat alone"], 1, -1.0),
        ("Sound cannot travel through:",
         ["Air", "Water", "Steel", "Vacuum"], 3, -0.5),
        ("The unit of frequency is:",
         ["Pascal", "Hertz", "Joule", "Watt"], 1, 0.0),
        ("The pitch of sound depends on:",
         ["Amplitude", "Frequency", "Speed of light", "Volume of room"], 1, 0.0),
        ("The audible range of frequencies for humans is:",
         ["10 Hz–10 kHz", "20 Hz–20 kHz", "100 Hz–100 kHz", "0–1000 Hz"], 1, 0.5),
    ],
    "C8S_CEEC": [
        ("A liquid that conducts electricity is called:",
         ["Insulator", "Electrolyte", "Dielectric", "Resistor"], 1, 0.0),
        ("Electroplating uses the principle of:",
         ["Electrolysis", "Magnetism", "Combustion", "Refraction"], 0, 0.5),
        ("In electroplating, the object to be coated acts as the:",
         ["Anode", "Cathode", "Electrolyte", "Bulb"], 1, 0.5),
        ("Distilled water is a:",
         ["Good conductor", "Poor conductor", "Insulator", "Magnet"], 1, -0.5),
        ("LED lights up when current passes through it because of:",
         ["Heating effect", "Magnetic effect", "Chemical effect", "All of these"], 2, 1.0),
    ],
    "C8S_NAT": [
        ("Charge developed when a polythene strip is rubbed with wool is:",
         ["Positive", "Negative", "No charge", "Both"], 1, 0.0),
        ("The instrument used to detect electric charge is:",
         ["Ammeter", "Voltmeter", "Electroscope", "Galvanometer"], 2, 0.5),
        ("Lightning is a:",
         ["Magnetic phenomenon", "Sound wave", "Large electric discharge", "Heat wave only"], 2, -0.5),
        ("The Richter scale measures:",
         ["Wind speed", "Earthquake magnitude", "Sea waves", "Pressure only"], 1, -0.5),
        ("Earthing of electrical appliances helps to:",
         ["Increase the current", "Prevent electric shock", "Improve performance", "Save power"], 1, 0.0),
    ],
    "C8S_STAR": [
        ("The brightest planet visible from Earth is:",
         ["Mars", "Venus", "Jupiter", "Saturn"], 1, 0.0),
        ("The natural satellite of Earth is:",
         ["Phobos", "Moon", "Titan", "Europa"], 1, -1.0),
        ("Distance to nearby stars is measured in:",
         ["Kilometres", "Light years", "Hours", "Centimetres"], 1, 0.5),
        ("A group of stars forming a recognisable pattern is called:",
         ["Galaxy", "Constellation", "Nebula", "Asterism"], 1, 0.0),
        ("Pole star appears stationary because:",
         ["It does not exist", "It is at Earth's rotational axis direction", "It is in the south", "It is closest to Earth"], 1, 0.5),
    ],
    "C8S_POLL": [
        ("Major cause of acid rain is:",
         ["Carbon monoxide", "Sulphur and nitrogen oxides", "Methane", "Ozone"], 1, 0.5),
        ("The protective layer in the stratosphere is:",
         ["Ozone layer", "Greenhouse layer", "Troposphere", "Mesosphere"], 0, 0.0),
        ("Greenhouse gases primarily cause:",
         ["Cooling", "Global warming", "Acid rain", "Tornadoes"], 1, -0.5),
        ("Eutrophication is caused by excess of:",
         ["Salt", "Nitrates and phosphates from fertilisers", "Plastic", "Oil only"], 1, 1.0),
        ("Which of these is a renewable, clean source of energy?",
         ["Coal", "Petrol", "Solar", "Diesel"], 2, -0.5),
    ],
    "C8S_SYN": [
        ("Rayon is also called:",
         ["Artificial silk", "Real cotton", "Wool", "Jute"], 0, 0.0),
        ("Polyester is made from:",
         ["Wool", "Petroleum products", "Animal hair", "Cotton"], 1, 0.0),
        ("PET stands for:",
         ["Plastic Energy Test", "Polyethylene Terephthalate", "Polymer Excess Type", "Pure Ethylene Total"], 1, 0.5),
        ("Plastics are classified into:",
         ["Hard and soft", "Thermoplastic and thermosetting", "Wet and dry", "Light and dark"], 1, 0.5),
        ("Bakelite is an example of:",
         ["Thermoplastic", "Thermosetting plastic", "Natural fibre", "Metallic alloy"], 1, 0.5),
    ],

    # ====================================================================
    # CLASS 8 — SOCIAL SCIENCE  (History → Geography → Civics)
    # ====================================================================
    "C8H_INTRO": [
        ("Modern Indian history primarily begins with:",
         ["Mughal era", "British colonial period", "Mauryan empire", "Vedic period"], 1, -0.5),
        ("Periodisation of history helps us:",
         ["Forget events", "Organise events into meaningful eras", "Remove dates", "Hide facts"], 1, 0.0),
        ("Census records and surveys are examples of:",
         ["Oral sources", "Official records as primary sources", "Archaeological data", "Folklore"], 1, 0.5),
        ("James Mill divided Indian history into three periods named after:",
         ["Dynasties", "Religions (Hindu, Muslim, British)", "Wars", "Languages"], 1, 0.5),
        ("Which is NOT a source for studying modern history?",
         ["Newspapers", "Letters and memoirs", "Photographs", "Cave paintings of pre-history"], 3, 0.0),
    ],
    "C8H_TRADE": [
        ("The English East India Company received its royal charter in:",
         ["1500", "1600", "1700", "1857"], 1, -0.5),
        ("Battle of Plassey was fought in:",
         ["1757", "1764", "1857", "1947"], 0, 0.0),
        ("After Plassey, the Company gained control of:",
         ["Maharashtra", "Bengal", "Punjab", "Madras"], 1, 0.0),
        ("Doctrine of Lapse was associated with:",
         ["Robert Clive", "Lord Dalhousie", "Warren Hastings", "Cornwallis"], 1, 0.5),
        ("Subsidiary alliance was introduced by:",
         ["Lord Wellesley", "Lord Cornwallis", "Robert Clive", "Lord Mountbatten"], 0, 0.5),
    ],
    "C8H_RULING": [
        ("Permanent Settlement was introduced by:",
         ["Lord Cornwallis", "Lord Dalhousie", "Warren Hastings", "Lord Curzon"], 0, 0.0),
        ("Under the Ryotwari system, revenue was paid by:",
         ["Zamindars", "The peasants directly", "Mahals", "Princes"], 1, 0.5),
        ("Indigo cultivation was concentrated in:",
         ["Punjab", "Bengal-Bihar", "South India", "Rajasthan"], 1, 0.5),
        ("The 'Blue Mutiny' or Indigo Revolt happened in:",
         ["1757", "1857", "1859–60", "1947"], 2, 0.5),
        ("Mahalwari settlement applied revenue assessment to:",
         ["Each peasant", "Each village (mahal)", "Each district", "Each state"], 1, 0.5),
    ],
    "C8H_TRIBAL": [
        ("Birsa Munda led a movement among:",
         ["Santhals", "Mundas", "Bhils", "Gonds"], 1, -0.5),
        ("Dikus refers to:",
         ["Tribal heroes", "Outsiders to the tribal regions", "Foreign rulers only", "Forest officers"], 1, 0.5),
        ("Pre-colonial tribals lived primarily by:",
         ["Industry", "Agriculture, hunting and gathering", "Banking", "Trade with Europe"], 1, 0.0),
        ("Forest laws under the British made many tribal practices:",
         ["Legal", "Illegal (e.g. shifting cultivation)", "Optional", "Subsidised"], 1, 0.5),
        ("Birsa Munda envisioned restoration of:",
         ["British rule", "A 'Munda Raj' / golden age", "Mughal empire", "Maratha empire"], 1, 0.5),
    ],
    "C8H_REBEL": [
        ("The Revolt of 1857 began at:",
         ["Delhi", "Meerut", "Kanpur", "Lucknow"], 1, 0.0),
        ("The immediate cause was the introduction of:",
         ["Income tax", "Greased cartridges (Enfield rifle)", "Railways", "English education"], 1, 0.0),
        ("The last Mughal emperor declared symbolic leader was:",
         ["Akbar II", "Bahadur Shah Zafar", "Aurangzeb", "Shah Alam"], 1, 0.0),
        ("After 1857 the rule of India passed from the Company to:",
         ["French", "British Crown", "Mughal Emperor", "East India trading houses"], 1, -0.5),
        ("Rani Lakshmibai led the revolt in:",
         ["Jhansi", "Awadh", "Delhi", "Punjab"], 0, -0.5),
    ],
    "C8H_NATL": [
        ("The Indian National Congress was founded in:",
         ["1857", "1885", "1905", "1947"], 1, -0.5),
        ("First president of the INC was:",
         ["W.C. Bonnerjee", "A.O. Hume", "Dadabhai Naoroji", "Tilak"], 0, 0.5),
        ("Partition of Bengal happened in:",
         ["1885", "1905", "1919", "1947"], 1, 0.0),
        ("'Swaraj is my birthright' was given by:",
         ["Gandhi", "Tilak", "Bose", "Nehru"], 1, 0.0),
        ("The Non-Cooperation Movement was launched by:",
         ["Tilak", "Gandhi", "Nehru", "Bose"], 1, -0.5),
    ],
    "C8G_RES": [
        ("Resources are classified on the basis of origin into:",
         ["Renewable and non-renewable only", "Biotic and abiotic", "Hot and cold", "Public and private only"], 1, 0.0),
        ("Solar energy is a:",
         ["Non-renewable resource", "Renewable resource", "Biotic resource", "Reserve only"], 1, -0.5),
        ("Petroleum is classified as:",
         ["Renewable", "Non-renewable", "Inexhaustible", "Biotic only"], 1, -0.5),
        ("Sustainable development means:",
         ["Use without limit", "Use that meets present needs without compromising future", "Stopping all use", "Using only abroad"], 1, 0.0),
        ("Stocks vs reserves: reserves are:",
         ["Untapped quantity", "Used up part", "The part of stock that can be used with current technology", "Always renewable"], 2, 1.0),
    ],
    "C8G_LSWVW": [
        ("Land used for growing crops is called:",
         ["Forest land", "Agricultural land", "Wasteland", "Pasture"], 1, -1.0),
        ("Soil is formed by the breakdown of:",
         ["Air only", "Rocks (weathering) and organic matter", "Water alone", "Plants only"], 1, 0.0),
        ("Water resources include:",
         ["Only oceans", "Surface and groundwater", "Air vapour only", "Glacier ice only"], 1, -0.5),
        ("Tropical evergreen forests are dense and have:",
         ["Hot dry summers", "Heavy rainfall and high temperatures", "Cold winters only", "Sparse vegetation"], 1, 0.5),
        ("National Parks aim to protect:",
         ["Industries", "Wildlife and habitat", "Mines", "Roads"], 1, -0.5),
    ],
    "C8G_MIN": [
        ("Minerals are classified into ferrous and:",
         ["Solid", "Non-ferrous", "Coloured", "Precious only"], 1, -0.5),
        ("An example of a non-conventional energy source is:",
         ["Coal", "Petroleum", "Solar", "Natural gas"], 2, -0.5),
        ("Iron, manganese and chromium are examples of:",
         ["Non-ferrous minerals", "Ferrous minerals", "Energy minerals", "Precious metals"], 1, 0.5),
        ("Hydroelectric power uses energy of:",
         ["Sun", "Wind", "Flowing water", "Coal"], 2, -0.5),
        ("Nuclear energy mainly uses:",
         ["Coal", "Uranium / thorium", "Solar panels", "Wood"], 1, 0.5),
    ],
    "C8G_AGRI": [
        ("Subsistence farming aims to:",
         ["Sell internationally", "Produce food primarily for the family", "Produce only cash crops", "Manufacture industrial goods"], 1, 0.0),
        ("Plantation agriculture grows:",
         ["Mixed crops", "A single cash crop on a large scale", "Only food grains", "Wild fruits"], 1, 0.5),
        ("Rice is mainly grown in regions with:",
         ["Cold and dry conditions", "High rainfall and warm climate", "Desert conditions", "Mountain peaks"], 1, -0.5),
        ("Wheat is mainly grown in:",
         ["Tropical wet regions", "Temperate regions", "Hot deserts", "Polar regions"], 1, 0.0),
        ("Mixed farming combines:",
         ["Two crops only", "Crop production with livestock", "Industries with farms", "Rice and wheat only"], 1, 0.5),
    ],
    "C8G_IND": [
        ("Industries are classified by raw material into:",
         ["Heavy and light only", "Agro-based and mineral-based", "Old and new", "Public only"], 1, 0.0),
        ("An example of an agro-based industry:",
         ["Iron and steel", "Sugar", "Cement", "Petroleum refining"], 1, -0.5),
        ("Iron and steel is a:",
         ["Light industry", "Heavy industry", "Cottage industry", "Service industry"], 1, 0.0),
        ("Industries in homes/villages with simple tools are:",
         ["Heavy", "Cottage / small-scale", "Multinational", "Plantation"], 1, -0.5),
        ("Information Technology (IT) industry deals with:",
         ["Steel", "Production and use of computer-based information", "Mining", "Cotton"], 1, -0.5),
    ],
    "C8G_HUM": [
        ("Population density is measured in:",
         ["People per square km", "People per litre", "Households per village", "Total population only"], 0, 0.0),
        ("World population growth has been:",
         ["Constant", "Rapidly increasing especially since 1800s", "Always falling", "Zero"], 1, 0.5),
        ("A factor influencing population distribution is:",
         ["Climate", "Cinema", "Sports", "Food preferences only"], 0, -0.5),
        ("Birth rate is the number of live births per:",
         ["100 people per year", "1000 people per year", "Million per decade", "Family"], 1, 0.5),
        ("Population pyramid shows:",
         ["Heights of buildings", "Distribution of age and sex of population", "Mountains", "Soil layers"], 1, 0.5),
    ],
    "C8C_CONST": [
        ("The Indian Constitution came into force on:",
         ["15 Aug 1947", "26 Jan 1950", "26 Nov 1949", "2 Oct 1950"], 1, -0.5),
        ("The Constitution describes India as a:",
         ["Monarchy", "Sovereign socialist secular democratic republic", "Theocracy", "Communist state"], 1, 0.0),
        ("Fundamental Rights are guaranteed under Part:",
         ["I", "III", "IV", "V"], 1, 0.5),
        ("The Indian Constitution was drafted by an Assembly chaired in drafting by:",
         ["Nehru", "B.R. Ambedkar (Drafting Committee)", "Gandhi", "Patel"], 1, 0.0),
        ("Right to Equality is a:",
         ["Directive principle", "Fundamental Right", "Fundamental Duty", "Preamble clause only"], 1, 0.0),
    ],
    "C8C_PARL": [
        ("The Parliament of India consists of:",
         ["Only Lok Sabha", "Only Rajya Sabha", "President + Lok Sabha + Rajya Sabha", "President alone"], 2, 0.0),
        ("Members of Lok Sabha are:",
         ["Nominated", "Directly elected by people", "Elected by State Assemblies only", "Hereditary"], 1, -0.5),
        ("Term of Lok Sabha is normally:",
         ["3 years", "4 years", "5 years", "6 years"], 2, 0.0),
        ("Money Bills can be introduced only in:",
         ["Lok Sabha", "Rajya Sabha", "Either House", "President's office"], 0, 0.5),
        ("The role of opposition is to:",
         ["Pass all bills without question", "Question and check the ruling party", "Form government", "Conduct elections"], 1, 0.0),
    ],
    "C8C_JUDIC": [
        ("Highest court of India is the:",
         ["High Court", "Supreme Court", "District Court", "Tribunal"], 1, -1.0),
        ("Independent judiciary means:",
         ["Free from interference of other branches", "Same as legislature", "Reports to executive", "Run by Parliament"], 0, 0.0),
        ("Public Interest Litigation (PIL) was introduced in the:",
         ["1950s", "1960s", "1970s–1980s", "1990s"], 2, 1.0),
        ("Subordinate courts are at the:",
         ["National level", "State level", "District and lower levels", "International level"], 2, 0.5),
        ("Right to access courts is a:",
         ["Privilege of rich", "Fundamental right", "Optional", "Reserved for officials"], 1, 0.5),
    ],
    "C8C_MARG": [
        ("Adivasis are also called:",
         ["Foreigners", "Indigenous / tribal communities", "Migrants only", "Industrialists"], 1, 0.0),
        ("Marginalisation means being:",
         ["Promoted", "Pushed to the edge of society without resources/recognition", "Honoured", "Exiled abroad"], 1, 0.5),
        ("Dalits face discrimination historically due to:",
         ["Climate", "Caste system", "Language", "Trade"], 1, 0.0),
        ("Article 17 of the Constitution abolishes:",
         ["Slavery", "Untouchability", "Child labour", "Bonded labour"], 1, 0.5),
        ("A Religious minority in India means a community:",
         ["Largest in number", "Smaller in number compared to majority", "Not recognised", "Without rights"], 1, 0.5),
    ],
    "C8C_PUB": [
        ("Public facilities are essential because:",
         ["Only the rich need them", "They ensure basic needs for all citizens", "They are free internationally only", "They earn government profit"], 1, 0.0),
        ("An example of a public facility is:",
         ["Private mall", "Public water supply", "Private school", "Private bank"], 1, -0.5),
        ("Article 21 of the Constitution guarantees:",
         ["Right to education", "Right to life and personal liberty", "Right to property", "Right to vote"], 1, 0.5),
        ("Privatisation of essential services may make them:",
         ["Cheaper for all", "Inaccessible to the poor at fair prices", "Disappear", "Mandatory"], 1, 0.5),
        ("The government provides public facilities because:",
         ["Markets alone may not ensure equity", "It earns more profit", "It is forced internationally", "It has nothing else to do"], 0, 0.5),
    ],
    "C8C_LAW": [
        ("Rule of law means:",
         ["Some are above law", "All are equal before law", "Government is above law", "Only judges follow law"], 1, 0.0),
        ("Bhopal Gas Tragedy is associated with:",
         ["1947", "1984", "1995", "2008"], 1, 0.0),
        ("A law that seeks to protect workers' rights is:",
         ["Income Tax Act", "Minimum Wages / Factories Act", "Currency Act", "Education Act"], 1, 0.5),
        ("The Right to Information Act was enacted in:",
         ["2002", "2005", "2010", "2012"], 1, 1.0),
        ("Environmental laws aim to:",
         ["Promote pollution", "Protect environment and public health", "Reduce taxes", "Increase tourism only"], 1, -0.5),
    ],

    # ====================================================================
    # CLASS 8 — ENGLISH
    # ====================================================================
    "C8E_HONEY": [
        ("'The Best Christmas Present in the World' is set in the time of:",
         ["First World War", "Second World War", "Indian Freedom Struggle", "Cold War"], 0, 0.5),
        ("The narrator in 'The Tsunami' (Honeydew) describes events in:",
         ["1947", "2004", "1971", "1999"], 1, 0.5),
        ("'Bepin Choudhury's Lapse of Memory' was authored by:",
         ["Ruskin Bond", "Satyajit Ray", "R.K. Narayan", "Rabindranath Tagore"], 1, 0.5),
        ("In 'The Summit Within', the summit refers to:",
         ["A mountain top alone", "Both a physical peak and a personal achievement", "A school summit", "A diplomatic meeting"], 1, 0.5),
        ("'A Visit to Cambridge' is a non-fictional account of meeting:",
         ["Tagore", "Stephen Hawking", "Newton", "Einstein"], 1, 0.0),
    ],
    "C8E_POEM": [
        ("'The Ant and the Cricket' is adapted from:",
         ["A Greek myth", "An Aesop's fable", "A Shakespeare play", "A modern novel"], 1, 0.0),
        ("In 'Geography Lesson', the poet observes earth from:",
         ["A boat", "An aeroplane", "A train", "A mountain top"], 1, 0.5),
        ("'Macavity: The Mystery Cat' was written by:",
         ["Robert Frost", "T.S. Eliot", "John Keats", "P.B. Shelley"], 1, 0.0),
        ("'On the Grasshopper and Cricket' celebrates:",
         ["Industry", "The continuity of the poetry of Earth", "Politics", "War"], 1, 0.5),
        ("Personification means:",
         ["Comparison using like/as", "Giving human qualities to non-humans", "Repetition of sounds", "Exaggeration only"], 1, -0.5),
    ],
    "C8E_ISH": [
        ("'How the Camel Got His Hump' is a story by:",
         ["R.K. Narayan", "Rudyard Kipling", "Tolstoy", "Chekhov"], 1, 0.0),
        ("'Children at Work' is about a child who:",
         ["Goes to school happily", "Runs away and finds work as a rag-picker", "Wins a trophy", "Travels abroad"], 1, 0.5),
        ("'The Open Window' (Saki) ends with a humorous:",
         ["Death", "Twist explaining the visitor's panic", "Wedding", "Lecture"], 1, 0.5),
        ("'Jalebis' is a story about a boy who succumbs to:",
         ["Anger", "Temptation of sweets bought with school fees", "Laziness", "Pride only"], 1, 0.0),
        ("'The Selfish Giant' was authored by:",
         ["Hans Andersen", "Oscar Wilde", "Charles Dickens", "Mark Twain"], 1, 0.5),
    ],
    "C8E_GRAM": [
        ("Choose the correct tense: 'She _____ to school every day.'",
         ["go", "goes", "going", "gone"], 1, -1.0),
        ("Active voice of 'The cake was eaten by him':",
         ["He eats the cake", "He ate the cake", "He has eaten the cake", "He had eaten the cake"], 1, 0.0),
        ("Reported speech: She said, \"I am happy.\" → She said that ____.",
         ["she is happy", "she was happy", "she will be happy", "she be happy"], 1, 0.5),
        ("Choose the correct preposition: 'The book is ____ the table.'",
         ["in", "on", "at", "by"], 1, -1.0),
        ("Identify the correct sentence:",
         ["He don't like apples", "He doesn't likes apples", "He doesn't like apples", "He not likes apples"], 2, 0.0),
    ],
    "C8E_READ": [
        ("Skimming a passage means:",
         ["Reading word by word slowly", "Reading quickly to get the gist", "Memorising it", "Translating it"], 1, 0.0),
        ("Inference means:",
         ["A direct quote", "A conclusion drawn from evidence", "A heading", "A list of words"], 1, 0.5),
        ("The main idea of a paragraph is best identified by:",
         ["Counting words", "Reading the topic and supporting sentences", "Looking at images only", "Skipping the paragraph"], 1, 0.0),
        ("'Vocabulary in context' means:",
         ["Memorise dictionary", "Guess word meaning from surrounding text", "Skip unknown words", "Translate every word"], 1, 0.5),
        ("Summary writing requires:",
         ["Adding new ideas", "Capturing main points concisely", "Repeating the passage", "Random selection"], 1, -0.5),
    ],
}
