"""CBSE Class 9 — full-syllabus MCQ seed bank.

Covers every NCERT Class 9 chapter NOT already present in the
``cbse_polymorphic`` seed (which ships Matter, Motion, Gravitation,
Number Systems, Polynomials, Triangles). Five PUBLISHED MCQ_SINGLE
questions per topic.

Tuple shape: ``(stem, [choice_a, choice_b, choice_c, choice_d],
correct_idx, difficulty_b)``. ``correct_idx`` is 0-based; ``difficulty_b``
is the IRT b-parameter on the conventional [-3, +3] scale (negative ⇒
easy, positive ⇒ hard).

Topic codes match the catalog migration ``019_seed_cbse_full_syllabus``.
"""

from __future__ import annotations

# (code, uuid) — must match alembic/catalog/versions/019_seed_cbse_full_syllabus.py
TOPIC_IDS: dict[str, str] = {
    # Class 9 Maths
    "C9M_COORD":   "33333333-0000-0000-0000-000000000088",
    "C9M_LIN2":    "33333333-0000-0000-0000-000000000089",
    "C9M_EUCL":    "33333333-0000-0000-0000-000000000090",
    "C9M_LA":      "33333333-0000-0000-0000-000000000091",
    "C9M_QUAD":    "33333333-0000-0000-0000-000000000092",
    "C9M_CIRC":    "33333333-0000-0000-0000-000000000093",
    "C9M_HER":     "33333333-0000-0000-0000-000000000094",
    "C9M_SAV":     "33333333-0000-0000-0000-000000000095",
    "C9M_STAT":    "33333333-0000-0000-0000-000000000096",
    # Class 9 Science
    "C9S_PURE":    "33333333-0000-0000-0000-000000000097",
    "C9S_ATOM":    "33333333-0000-0000-0000-000000000098",
    "C9S_STRUC":   "33333333-0000-0000-0000-000000000099",
    "C9S_CELL":    "33333333-0000-0000-0000-000000000100",
    "C9S_TIS":     "33333333-0000-0000-0000-000000000101",
    "C9S_FORCE":   "33333333-0000-0000-0000-000000000102",
    "C9S_WE":      "33333333-0000-0000-0000-000000000103",
    "C9S_SOUND":   "33333333-0000-0000-0000-000000000104",
    "C9S_FOOD":    "33333333-0000-0000-0000-000000000105",
    # Class 9 Social Science
    "C9H_FRENCH":  "33333333-0000-0000-0000-000000000106",
    "C9H_RUSSIA":  "33333333-0000-0000-0000-000000000107",
    "C9H_NAZI":    "33333333-0000-0000-0000-000000000108",
    "C9H_FOREST":  "33333333-0000-0000-0000-000000000109",
    "C9H_PASTOR":  "33333333-0000-0000-0000-000000000110",
    "C9G_LOC":     "33333333-0000-0000-0000-000000000111",
    "C9G_PHY":     "33333333-0000-0000-0000-000000000112",
    "C9G_DRAIN":   "33333333-0000-0000-0000-000000000113",
    "C9G_CLIM":    "33333333-0000-0000-0000-000000000114",
    "C9G_VEG":     "33333333-0000-0000-0000-000000000115",
    "C9G_POP":     "33333333-0000-0000-0000-000000000116",
    "C9P_DEMO":    "33333333-0000-0000-0000-000000000117",
    "C9P_CONST":   "33333333-0000-0000-0000-000000000118",
    "C9P_ELEC":    "33333333-0000-0000-0000-000000000119",
    "C9P_INST":    "33333333-0000-0000-0000-000000000120",
    "C9P_RIGHTS":  "33333333-0000-0000-0000-000000000121",
    "C9E_PALAM":   "33333333-0000-0000-0000-000000000122",
    "C9E_PEOP":    "33333333-0000-0000-0000-000000000123",
    "C9E_POV":     "33333333-0000-0000-0000-000000000124",
    "C9E_FOOD":    "33333333-0000-0000-0000-000000000125",
    # Class 9 English
    "C9E_BEEHIVE": "33333333-0000-0000-0000-000000000126",
    "C9E_POEM":    "33333333-0000-0000-0000-000000000127",
    "C9E_MOM":     "33333333-0000-0000-0000-000000000128",
    "C9E_GRAM":    "33333333-0000-0000-0000-000000000129",
    "C9E_READ":    "33333333-0000-0000-0000-000000000130",
}


# Tuple shape: (stem, choices, correct_idx, difficulty_b)
TOPIC_QUESTIONS: dict[str, list[tuple[str, list[str], int, float]]] = {
    # ====================================================================
    # CLASS 9 — MATHEMATICS
    # ====================================================================
    "C9M_COORD": [
        ("The point (3, 0) lies on:",
         ["x-axis", "y-axis", "First quadrant", "Origin"], 0, -0.5),
        ("In which quadrant does the point (−4, 5) lie?",
         ["I", "II", "III", "IV"], 1, 0.0),
        ("Coordinates of the origin are:",
         ["(0,0)", "(1,1)", "(0,1)", "(1,0)"], 0, -1.0),
        ("Distance of point (5,0) from y-axis is:",
         ["0", "5", "−5", "Cannot be found"], 1, 0.0),
        ("Abscissa of point P(7, −2) is:",
         ["−2", "7", "0", "5"], 1, 0.0),
    ],
    "C9M_LIN2": [
        ("A linear equation in two variables has the form:",
         ["ax² + bx + c = 0", "ax + by + c = 0", "x + y = constant only", "ax = b"], 1, 0.0),
        ("Solution of x + y = 5 is satisfied by:",
         ["(2,3)", "(1,1)", "(0,0)", "(2,2)"], 0, -0.5),
        ("Graph of x + y = 0 passes through:",
         ["Origin only", "Origin and (1, −1)", "Only II quadrant", "Only x-axis"], 1, 0.5),
        ("Equation of x-axis is:",
         ["x = 0", "y = 0", "x + y = 0", "x − y = 0"], 1, 0.0),
        ("Number of solutions of a single linear equation in two variables:",
         ["One", "Two", "Infinite", "Zero"], 2, 0.5),
    ],
    "C9M_EUCL": [
        ("A statement accepted as true without proof is a/an:",
         ["Theorem", "Conjecture", "Axiom or postulate", "Corollary"], 2, -0.5),
        ("Euclid's first postulate: A straight line may be drawn from any one point to:",
         ["Itself", "Another point", "Many points at once", "A curve"], 1, 0.0),
        ("Things equal to the same thing are:",
         ["Different", "Equal to one another", "Unrelated", "Smaller"], 1, -0.5),
        ("Geometry as we know it was systematised in the book:",
         ["The Republic", "Elements (Euclid)", "Principia", "Almagest"], 1, 0.0),
        ("Two distinct lines cannot have more than ____ point in common.",
         ["zero", "one", "two", "many"], 1, 0.5),
    ],
    "C9M_LA": [
        ("Sum of angles on a straight line is:",
         ["90°", "180°", "270°", "360°"], 1, -1.0),
        ("Two angles whose sum is 90° are called:",
         ["Supplementary", "Complementary", "Linear pair", "Vertical"], 1, -0.5),
        ("If two parallel lines are cut by a transversal, alternate interior angles are:",
         ["Supplementary", "Complementary", "Equal", "Right"], 2, 0.0),
        ("Sum of angles in a triangle is:",
         ["90°", "180°", "270°", "360°"], 1, -1.0),
        ("Angles in a linear pair are:",
         ["Equal", "Complementary", "Supplementary", "Vertical"], 2, 0.0),
    ],
    "C9M_QUAD": [
        ("Each angle of a rectangle is:",
         ["60°", "90°", "120°", "180°"], 1, -1.0),
        ("Diagonals of a parallelogram:",
         ["Are perpendicular", "Bisect each other", "Are equal", "Bisect at 60°"], 1, 0.0),
        ("A quadrilateral whose all sides are equal is a:",
         ["Rectangle", "Rhombus", "Trapezium", "Kite"], 1, 0.0),
        ("Mid-point theorem: line joining midpoints of two sides of a triangle is parallel to the third side and:",
         ["Equal to it", "Half of it", "Twice of it", "Perpendicular to it"], 1, 0.5),
        ("Diagonals of a square are equal AND:",
         ["Parallel", "Bisect each other at right angles", "Curved", "Unequal"], 1, 0.5),
    ],
    "C9M_CIRC": [
        ("Equal chords of a circle are at:",
         ["Different distances from centre", "Equal distances from centre", "Both ends of diameter only", "Right angles"], 1, 0.5),
        ("Angle in a semicircle is:",
         ["45°", "60°", "90°", "180°"], 2, 0.0),
        ("The longest chord of a circle is the:",
         ["Radius", "Diameter", "Tangent", "Sector boundary"], 1, -1.0),
        ("Angle subtended at the centre by an arc is ____ the angle subtended at any point on the remaining arc.",
         ["Half", "Twice", "Equal to", "Independent of"], 1, 0.5),
        ("Quadrilateral inscribed in a circle is called:",
         ["Square", "Cyclic quadrilateral", "Rhombus", "Trapezium"], 1, 0.0),
    ],
    "C9M_HER": [
        ("Heron's formula uses the semi-perimeter:",
         ["s = a+b+c", "s = (a+b+c)/2", "s = (a+b+c)/3", "s = abc"], 1, 0.0),
        ("Area of a triangle with sides 3, 4, 5 cm by Heron's formula:",
         ["6 cm²", "10 cm²", "12 cm²", "20 cm²"], 0, 0.5),
        ("Heron's formula is most useful when:",
         ["Triangle is right-angled and base/height known", "Only sides are known", "Only angles known", "Triangle is equilateral only"], 1, 0.5),
        ("Square root of 36 is:",
         ["4", "5", "6", "9"], 2, -1.0),
        ("Area of an equilateral triangle of side a using Heron is:",
         ["a²", "(√3/4) a²", "(1/2)·a²", "(3/4)·a²"], 1, 1.0),
    ],
    "C9M_SAV": [
        ("Volume of a cuboid with l=2, b=3, h=4 is:",
         ["12", "20", "24", "30"], 2, -0.5),
        ("Surface area of a sphere of radius r:",
         ["πr²", "2πr²", "4πr²", "(4/3)πr³"], 2, 0.5),
        ("Volume of a cylinder of radius r and height h:",
         ["πrh", "πr²h", "2πrh", "(1/3)πr²h"], 1, 0.0),
        ("Curved surface area of a cone of radius r and slant height l:",
         ["πrl", "πr²l", "2πrl", "(1/2)πrl"], 0, 0.5),
        ("Volume of a hemisphere of radius r is:",
         ["(2/3)πr³", "(4/3)πr³", "πr³", "(1/3)πr²"], 0, 0.5),
    ],
    "C9M_STAT": [
        ("Mean of 2, 4, 6, 8, 10 is:",
         ["4", "5", "6", "8"], 2, -0.5),
        ("Median of 3, 5, 7, 9, 11 is:",
         ["5", "7", "9", "8"], 1, -0.5),
        ("Mode is the value that:",
         ["Appears most frequently", "Has middle position", "Equals the mean", "Is largest"], 0, -0.5),
        ("Range of data 5, 8, 12, 17, 22:",
         ["12", "17", "22", "27"], 1, 0.0),
        ("If the data is skewed, the best measure of central tendency is often:",
         ["Mean", "Median", "Mode", "Range"], 1, 1.0),
    ],

    # ====================================================================
    # CLASS 9 — SCIENCE
    # ====================================================================
    "C9S_PURE": [
        ("A pure substance contains:",
         ["Only one kind of particle", "Two or more particles randomly", "Insoluble matter", "Air bubbles"], 0, -0.5),
        ("Brass is an example of:",
         ["A compound", "A homogeneous mixture (alloy)", "An element", "A heterogeneous mixture only"], 1, 0.5),
        ("A solution that can dissolve no more solute at a given temperature is:",
         ["Unsaturated", "Dilute", "Saturated", "Concentrated only"], 2, 0.0),
        ("Tyndall effect is shown by:",
         ["True solutions", "Colloids", "Pure liquids only", "Crystals"], 1, 0.5),
        ("Method to separate dye components in ink is:",
         ["Distillation", "Chromatography", "Filtration", "Sedimentation"], 1, 0.5),
    ],
    "C9S_ATOM": [
        ("Law of conservation of mass states that mass is:",
         ["Created in reactions", "Destroyed in reactions", "Conserved in chemical reactions", "Always increasing"], 2, 0.0),
        ("The molecular formula of water is:",
         ["H2", "H2O", "HO2", "OH"], 1, -1.0),
        ("Number of atoms in 1 mole of any element is approximately:",
         ["6.022 × 10²²", "6.022 × 10²³", "6.022 × 10²⁴", "6.022 × 10²¹"], 1, 0.5),
        ("Atomic mass unit (amu) is defined relative to:",
         ["Hydrogen-1", "Carbon-12", "Oxygen-16", "Helium-4"], 1, 0.5),
        ("If 12 g of carbon contain 1 mole, then 24 g contain:",
         ["0.5 mol", "1 mol", "2 mol", "12 mol"], 2, 0.0),
    ],
    "C9S_STRUC": [
        ("Discovery of the electron is credited to:",
         ["Rutherford", "J.J. Thomson", "Bohr", "Chadwick"], 1, 0.0),
        ("Atomic number equals the number of:",
         ["Neutrons", "Protons", "Nucleons", "Electrons in valence shell"], 1, -0.5),
        ("Mass number equals:",
         ["Protons − neutrons", "Protons + electrons", "Protons + neutrons", "Electrons only"], 2, 0.0),
        ("Maximum electrons in the K-shell is:",
         ["2", "8", "18", "32"], 0, -0.5),
        ("Isotopes have the same:",
         ["Mass number", "Atomic number, different mass numbers", "Number of neutrons", "Charge"], 1, 0.5),
    ],
    "C9S_CELL": [
        ("Cell theory was proposed by:",
         ["Hooke and Leeuwenhoek", "Schleiden and Schwann", "Watson and Crick", "Darwin and Wallace"], 1, 0.5),
        ("Powerhouse of the cell is:",
         ["Nucleus", "Mitochondria", "Ribosome", "Chloroplast"], 1, -0.5),
        ("Selectively permeable membrane around a cell is the:",
         ["Cell wall", "Plasma membrane", "Nuclear membrane", "Lysosome"], 1, 0.0),
        ("Prokaryotes lack a:",
         ["Cell membrane", "Cytoplasm", "Defined nucleus (membrane-bound)", "DNA"], 2, 0.5),
        ("Suicide bag of the cell is:",
         ["Lysosome", "Vacuole", "Mitochondria", "Ribosome"], 0, 0.5),
    ],
    "C9S_TIS": [
        ("Plant tissues that grow continuously are called:",
         ["Permanent", "Meristematic", "Phloem only", "Sclerenchyma"], 1, 0.0),
        ("Xylem transports:",
         ["Food", "Water and minerals upward", "Hormones only", "Oxygen only"], 1, -0.5),
        ("Phloem transports:",
         ["Water", "Sugars/food prepared by leaves", "Minerals only", "Air"], 1, -0.5),
        ("Animal tissue that connects organs and provides support is:",
         ["Epithelial", "Connective", "Muscular", "Nervous"], 1, 0.0),
        ("Striated muscles are also called:",
         ["Smooth", "Skeletal/voluntary", "Cardiac only", "Involuntary"], 1, 0.5),
    ],
    "C9S_FORCE": [
        ("Newton's first law is also called:",
         ["Law of momentum", "Law of inertia", "Law of action-reaction", "Law of friction"], 1, -0.5),
        ("F = m·a is which law of motion?",
         ["First", "Second", "Third", "Hooke's"], 1, -0.5),
        ("Newton's third law: every action has an:",
         ["Equal and opposite reaction", "Equal reaction in same direction", "Smaller reaction", "Random reaction"], 0, -0.5),
        ("Momentum is the product of:",
         ["Force and time", "Mass and velocity", "Mass and acceleration", "Force and distance"], 1, 0.0),
        ("SI unit of momentum is:",
         ["kg·m/s²", "kg·m/s", "N·m", "kg·s"], 1, 0.5),
    ],
    "C9S_WE": [
        ("Work done = force × ____.",
         ["Time", "Distance in direction of force", "Acceleration", "Mass"], 1, -0.5),
        ("SI unit of work and energy is:",
         ["Newton", "Joule", "Watt", "Pascal"], 1, -1.0),
        ("Kinetic energy of an object of mass m and speed v:",
         ["m·v", "(1/2)mv²", "m·g·h", "(1/2)mv"], 1, 0.0),
        ("Power is the rate of doing:",
         ["Force", "Work", "Pressure", "Acceleration"], 1, -0.5),
        ("1 watt equals:",
         ["1 J/s", "1 N·m", "1 N/s", "1 J·s"], 0, 0.0),
    ],
    "C9S_SOUND": [
        ("Sound is a form of:",
         ["Transverse wave", "Longitudinal mechanical wave", "Electromagnetic wave", "Standing wave only"], 1, 0.0),
        ("Speed of sound is highest in:",
         ["Vacuum", "Air", "Water", "Steel"], 3, 0.0),
        ("SONAR uses:",
         ["Light", "Ultrasound", "Microwaves", "X-rays"], 1, 0.5),
        ("Echo can be heard if reflecting surface is at least ____ away (in air at 20°C).",
         ["1 m", "5 m", "17 m", "100 m"], 2, 0.5),
        ("Loudness depends on:",
         ["Frequency", "Amplitude", "Wavelength only", "Pitch only"], 1, 0.0),
    ],
    "C9S_FOOD": [
        ("Cross-breeding aims to combine desirable traits from:",
         ["Same variety only", "Two genetically different varieties", "Wild plants only", "Single parent"], 1, 0.5),
        ("Animal husbandry is the scientific management of:",
         ["Forests", "Livestock", "Fisheries only", "Wildlife only"], 1, -0.5),
        ("Apiculture refers to the rearing of:",
         ["Birds", "Bees for honey", "Cattle", "Fish"], 1, 0.0),
        ("Composite fish culture uses:",
         ["A single species", "Multiple compatible species in the same pond", "Only marine fish", "Frogs only"], 1, 0.5),
        ("Hybridisation in crops increases:",
         ["Vulnerability only", "Yield, disease resistance and quality", "Cost only", "Bitterness"], 1, -0.5),
    ],

    # ====================================================================
    # CLASS 9 — SOCIAL SCIENCE
    # ====================================================================
    "C9H_FRENCH": [
        ("The French Revolution began in:",
         ["1689", "1789", "1889", "1689"], 1, -0.5),
        ("The storming of the Bastille happened on:",
         ["14 July 1789", "26 January 1789", "4 July 1789", "14 July 1799"], 0, 0.0),
        ("Pre-revolution French society was divided into:",
         ["Two estates", "Three estates", "Four estates", "Five estates"], 1, 0.0),
        ("'The Spirit of the Laws' was authored by:",
         ["Rousseau", "Montesquieu", "Voltaire", "Robespierre"], 1, 0.5),
        ("The Declaration of the Rights of Man was passed in:",
         ["1789", "1793", "1799", "1815"], 0, 0.5),
    ],
    "C9H_RUSSIA": [
        ("The October Revolution in Russia took place in:",
         ["1905", "1914", "1917", "1924"], 2, -0.5),
        ("The Bolshevik leader was:",
         ["Trotsky", "Lenin", "Stalin", "Kerensky"], 1, 0.0),
        ("After 1917 Russia became the:",
         ["German Empire", "USSR / Soviet Union", "Yugoslavia", "Republic of Texas"], 1, -0.5),
        ("Liberals in 19th-century Europe wanted:",
         ["Absolute monarchy", "Nation tolerant of all religions, govt by elected representatives", "Communism", "Theocracy"], 1, 0.5),
        ("Collectivisation of agriculture is associated with:",
         ["Lenin", "Stalin", "Tsar Nicholas II", "Trotsky"], 1, 0.5),
    ],
    "C9H_NAZI": [
        ("Adolf Hitler became Chancellor of Germany in:",
         ["1923", "1933", "1939", "1945"], 1, -0.5),
        ("The Treaty of Versailles was signed after:",
         ["WW2", "WW1", "Cold War", "Crimean War"], 1, 0.0),
        ("The Holocaust refers to the genocide primarily of:",
         ["Italians", "Jews and other targeted groups", "Russians only", "Africans only"], 1, 0.0),
        ("Weimar Republic was the German government from:",
         ["1871–1918", "1918–1933", "1933–1945", "1945–1990"], 1, 0.5),
        ("'Mein Kampf' was written by:",
         ["Stalin", "Hitler", "Mussolini", "Lenin"], 1, 0.0),
    ],
    "C9H_FOREST": [
        ("Scientific forestry under colonial rule meant:",
         ["Local control of forests", "State-managed plantation forestry of selected species", "Return to traditional use", "No use of forests"], 1, 0.5),
        ("The Forest Act in colonial India was first enacted in:",
         ["1865 / 1878", "1947", "1957", "1995"], 0, 0.5),
        ("Bastar rebellion (1910) was led against:",
         ["Mughals", "Princely state forest reservation under colonial regime", "Maratha rule", "Italian invaders"], 1, 0.5),
        ("Shifting cultivation is also called:",
         ["Plantation farming", "Slash-and-burn / jhum", "Mixed farming only", "Dry farming"], 1, 0.0),
        ("'Reserved' forests under colonial classification were:",
         ["Open for villagers", "Most strictly preserved, off-limits", "Used for grazing only", "Sold to peasants"], 1, 0.5),
    ],
    "C9H_PASTOR": [
        ("Pastoralists are people who:",
         ["Live only in cities", "Move with herds in search of pasture", "Cultivate fixed land only", "Mine ores"], 1, 0.0),
        ("The Maasai are pastoralists from:",
         ["South America", "East Africa", "Europe", "South-East Asia"], 1, 0.5),
        ("In India, Gujjar Bakarwals graze in:",
         ["Coastal Tamil Nadu", "Jammu and Kashmir mountains", "Kerala backwaters", "Punjab plains only"], 1, 0.5),
        ("Colonial laws like Wasteland Rules affected pastoralists by:",
         ["Granting more land", "Reducing grazing land", "Free housing", "No effect"], 1, 0.5),
        ("Pastoralism still exists today because it:",
         ["Has died out", "Continues to be ecologically and economically viable in dry zones", "Is illegal everywhere", "Is replaced by mining"], 1, 0.0),
    ],
    "C9G_LOC": [
        ("India lies entirely in the:",
         ["Southern Hemisphere", "Northern Hemisphere", "Eastern Hemisphere only", "Western Hemisphere"], 1, -0.5),
        ("The Tropic of Cancer passes through:",
         ["Southern India", "Central India", "Northern India only", "It does not pass through India"], 1, 0.0),
        ("The standard meridian of India is:",
         ["75°30'E", "82°30'E", "90°30'E", "23°30'N"], 1, 0.5),
        ("India's southernmost point on the mainland is:",
         ["Kanyakumari", "Indira Point", "Cape Comorin (= Kanyakumari)", "Kavaratti"], 0, 0.5),
        ("Indian Ocean is to India's:",
         ["North", "South", "East", "West"], 1, -1.0),
    ],
    "C9G_PHY": [
        ("The Himalayas were formed by:",
         ["Volcanic eruption only", "Collision of Indian and Eurasian plates", "Glacial action only", "Erosion alone"], 1, 0.5),
        ("Indo-Gangetic plain is formed by:",
         ["Volcanic ash", "Alluvial deposits of rivers", "Sand from desert", "Coral reef"], 1, 0.0),
        ("The highest peak of India is:",
         ["Everest (in Nepal)", "Kanchenjunga (Indian peak)", "K2 (border)", "Mount Abu"], 1, 0.5),
        ("Thar desert lies in:",
         ["West Bengal", "Rajasthan", "Tamil Nadu", "Sikkim"], 1, -0.5),
        ("The Deccan Plateau is bordered by:",
         ["Aravalli only", "Western Ghats and Eastern Ghats", "Himalayas only", "Vindhyas alone"], 1, 0.5),
    ],
    "C9G_DRAIN": [
        ("Indian rivers are classified into:",
         ["Northern only", "Himalayan and Peninsular", "Coastal only", "Inland only"], 1, 0.0),
        ("Ganga rises from:",
         ["Mansarovar", "Gangotri glacier", "Kailash", "Yamunotri only"], 1, 0.0),
        ("The longest river of peninsular India is:",
         ["Krishna", "Godavari", "Cauvery", "Mahanadi"], 1, 0.5),
        ("A river that drains into the Arabian Sea is:",
         ["Ganga", "Narmada", "Mahanadi", "Brahmaputra"], 1, 0.5),
        ("Wular Lake is in:",
         ["Rajasthan", "Jammu and Kashmir", "Karnataka", "Odisha"], 1, 0.5),
    ],
    "C9G_CLIM": [
        ("The Indian climate is dominated by the:",
         ["Westerlies", "Monsoon winds", "Trade winds only", "Polar winds"], 1, -0.5),
        ("South-west monsoon arrives in India around:",
         ["February", "Early June", "September", "December"], 1, 0.0),
        ("Mawsynram (Meghalaya) is famous for:",
         ["Lowest rainfall", "Highest annual rainfall in the world", "Coldest temperature", "Strongest winds"], 1, 0.0),
        ("Mango showers refer to pre-monsoon showers in:",
         ["Punjab", "Kerala and Karnataka", "Rajasthan", "Sikkim"], 1, 0.5),
        ("Loo is a:",
         ["Cold wind in Himalayas", "Hot dry wind in northern plains in summer", "Light coastal wind", "Tornado"], 1, 0.5),
    ],
    "C9G_VEG": [
        ("Tropical evergreen forests are found mainly in:",
         ["Rajasthan", "Western Ghats and North-East", "Himachal Pradesh", "Punjab"], 1, 0.0),
        ("Mangrove forests are typical of:",
         ["Mountain peaks", "Sundarbans delta", "Thar desert", "Plateaus"], 1, 0.0),
        ("National animal of India is:",
         ["Lion", "Tiger", "Elephant", "Peacock"], 1, -1.0),
        ("National bird of India is:",
         ["Eagle", "Peacock", "Parrot", "Sparrow"], 1, -1.0),
        ("Project Tiger was launched in:",
         ["1947", "1973", "1992", "2010"], 1, 0.5),
    ],
    "C9G_POP": [
        ("Census in India is conducted every:",
         ["5 years", "10 years", "20 years", "Every year"], 1, -0.5),
        ("Population density (per sq km) is:",
         ["Total population × area", "Total population ÷ area", "Births × deaths", "Migration only"], 1, 0.0),
        ("The state with the highest population in India (per recent census) is:",
         ["Maharashtra", "Uttar Pradesh", "Bihar", "Tamil Nadu"], 1, 0.0),
        ("Sex ratio is the number of females per:",
         ["100 males", "1000 males", "10000 males", "10 males"], 1, 0.5),
        ("Literacy rate is the percentage of population aged 7+ who can:",
         ["Speak only", "Read, write and understand a language", "Read English only", "Sign their name only"], 1, 0.5),
    ],
    "C9P_DEMO": [
        ("Democracy is a form of government in which rulers are:",
         ["Hereditary", "Chosen by the people", "Selected by judges", "Selected by army"], 1, -0.5),
        ("A key feature of democracy is:",
         ["Single party rule", "Free and fair elections", "Lifelong leaders", "No opposition"], 1, -0.5),
        ("Universal adult franchise means:",
         ["Voting only by educated", "Right to vote for all adults", "Voting only for men", "Voting only by taxpayers"], 1, 0.0),
        ("An argument for democracy is that it:",
         ["Speeds decisions only", "Improves quality of decision-making and accountability", "Reduces dissent only", "Eliminates problems instantly"], 1, 0.5),
        ("Which country is NOT typically classified as a democracy?",
         ["India", "USA", "North Korea", "France"], 2, 0.5),
    ],
    "C9P_CONST": [
        ("The Indian Constitution was adopted on:",
         ["15 Aug 1947", "26 Nov 1949", "26 Jan 1950", "2 Oct 1950"], 1, 0.0),
        ("Chairman of the Drafting Committee was:",
         ["Nehru", "B.R. Ambedkar", "Patel", "Tagore"], 1, -0.5),
        ("The Preamble describes India as:",
         ["A monarchy", "Sovereign socialist secular democratic republic", "A theocracy", "A confederation"], 1, 0.0),
        ("Right to Constitutional Remedies is given by Article:",
         ["14", "21", "32", "44"], 2, 1.0),
        ("South African Constitution influenced India's idea of:",
         ["Federalism", "Bill of rights and inclusive nationhood", "Cabinet system", "Money bills"], 1, 1.0),
    ],
    "C9P_ELEC": [
        ("Elections in India are conducted by the:",
         ["Parliament", "Election Commission of India", "President alone", "Supreme Court"], 1, -0.5),
        ("Voting age in India was reduced to 18 by which amendment?",
         ["42nd", "44th", "61st", "73rd"], 2, 1.0),
        ("A constituency is:",
         ["A government office", "A geographical area from which a representative is elected", "A type of political party", "A judicial body"], 1, 0.0),
        ("First-Past-The-Post system means:",
         ["Proportional representation", "Candidate with most votes wins", "Run-off voting", "Voting by lot"], 1, 0.5),
        ("Reservation of seats for SCs/STs is meant to ensure:",
         ["Permanent power", "Fair representation in legislatures", "Higher salaries", "Tax exemptions"], 1, 0.5),
    ],
    "C9P_INST": [
        ("The head of the Government of India is the:",
         ["President", "Prime Minister", "Chief Justice", "Speaker"], 1, -0.5),
        ("Council of Ministers is collectively responsible to the:",
         ["President", "Lok Sabha", "Rajya Sabha", "Supreme Court"], 1, 0.5),
        ("Bureaucracy implements:",
         ["Laws made by Parliament under political direction", "Religious decrees", "Family customs", "Court verdicts only"], 0, 0.5),
        ("Highest court of appeal in India is:",
         ["High Court", "Supreme Court", "Tribunal", "District Court"], 1, -1.0),
        ("The Speaker presides over:",
         ["Rajya Sabha", "Lok Sabha", "Cabinet", "Supreme Court"], 1, 0.0),
    ],
    "C9P_RIGHTS": [
        ("Fundamental Rights are guaranteed by Part:",
         ["I", "III", "IV", "V"], 1, 0.5),
        ("Right against exploitation prohibits:",
         ["Free speech", "Trafficking and forced labour", "Religious worship", "Owning property"], 1, 0.5),
        ("Right to Education was added by which amendment?",
         ["73rd", "86th", "92nd", "100th"], 1, 1.0),
        ("Right to Freedom (Article 19) includes the freedom of:",
         ["Speech and expression", "Religion only", "Property only", "Trade only"], 0, 0.5),
        ("The Right to Constitutional Remedies allows citizens to:",
         ["Vote in elections", "Move courts to enforce Fundamental Rights", "Pay taxes", "Migrate freely"], 1, 0.5),
    ],
    "C9E_PALAM": [
        ("In 'The Story of Village Palampur', the main occupation of villagers is:",
         ["Mining", "Farming", "Manufacturing aircraft", "Banking"], 1, -0.5),
        ("The four factors of production are:",
         ["Land, labour, capital, enterprise", "Land, water, food, fuel", "Houses, cars, money, gold", "Roads, schools, banks, hospitals"], 0, 0.0),
        ("MSP stands for:",
         ["Maximum Selling Price", "Minimum Support Price", "Market Sale Price", "Mid-Season Price"], 1, 0.5),
        ("Multiple cropping means:",
         ["Growing only one crop", "Growing more than one crop on same land in a year", "Importing crops", "Growing fruit trees only"], 1, 0.0),
        ("Modern farming inputs include:",
         ["HYV seeds, fertilisers, irrigation", "Wooden ploughs only", "Manual sowing only", "No machinery"], 0, 0.0),
    ],
    "C9E_PEOP": [
        ("Human capital refers to:",
         ["Money in banks", "Stock of skill and knowledge in people", "Buildings and machinery", "Natural resources"], 1, 0.5),
        ("Population is an asset when:",
         ["It is uneducated", "It is educated and healthy and productive", "It migrates abroad only", "It is large only"], 1, 0.0),
        ("Disguised unemployment is common in:",
         ["IT sector", "Agricultural sector with surplus labour", "Banking", "Mining"], 1, 0.5),
        ("Seasonal unemployment occurs primarily in:",
         ["Industry", "Agriculture", "Services only", "Transport"], 1, 0.0),
        ("Investment in education and health primarily increases:",
         ["Physical capital only", "Human capital", "Foreign loans", "Neither"], 1, 0.0),
    ],
    "C9E_POV": [
        ("Poverty line is defined in terms of:",
         ["Vehicle ownership", "Consumption / income criteria", "Number of relatives", "Mobile phones"], 1, 0.0),
        ("A 'vulnerable group' for poverty in India includes:",
         ["Salaried urban professionals", "Scheduled castes/tribes and landless labourers", "Industrialists", "Public sector officers"], 1, 0.5),
        ("MGNREGA guarantees ____ days of employment per rural household per year.",
         ["50", "75", "100", "365"], 2, 0.5),
        ("PMGSY aims to provide:",
         ["Housing in cities", "All-weather rural roads connectivity", "Free electricity", "Cooking gas only"], 1, 0.5),
        ("Self-help groups (SHGs) help reduce poverty by:",
         ["Banking through small savings and credit among members", "Lending only abroad", "Building factories", "Issuing currency"], 0, 0.5),
    ],
    "C9E_FOOD": [
        ("Food security has the dimensions of availability, accessibility and:",
         ["Acceptability/affordability", "Marketing", "Pollution", "Migration"], 0, 0.5),
        ("Buffer stock is maintained by:",
         ["RBI", "FCI (Food Corporation of India)", "Private firms only", "Foreign agencies"], 1, 0.5),
        ("PDS stands for:",
         ["Public Distribution System", "Private Direct Sale", "Personal Defence Service", "Postal Delivery System"], 0, 0.0),
        ("AAY (Antyodaya Anna Yojana) targets:",
         ["Industrialists", "Poorest of the poor", "Foreign tourists", "Government officers"], 1, 0.5),
        ("Green Revolution in India primarily increased production of:",
         ["Pulses only", "Wheat and rice", "Coffee only", "Cotton only"], 1, 0.0),
    ],

    # ====================================================================
    # CLASS 9 — ENGLISH
    # ====================================================================
    "C9E_BEEHIVE": [
        ("'The Fun They Had' is set in the future and depicts schooling that is:",
         ["Traditional with classrooms", "Mechanical/computer-based at home", "Outdoor only", "Only oral"], 1, 0.5),
        ("'The Sound of Music — Part I' is about Evelyn Glennie who:",
         ["Lost her sight", "Became a percussionist despite hearing impairment", "Is a famous painter", "Is a chef"], 1, 0.5),
        ("'The Little Girl' (Beehive) is a story of a girl learning to understand her:",
         ["Mother", "Father", "Brother", "Cousin"], 1, 0.5),
        ("'A Truly Beautiful Mind' is about:",
         ["Newton", "Einstein", "Tagore", "Darwin"], 1, 0.0),
        ("'My Childhood' (Beehive) is an autobiographical excerpt by:",
         ["Mahatma Gandhi", "A.P.J. Abdul Kalam", "R.K. Narayan", "Tagore"], 1, 0.0),
    ],
    "C9E_POEM": [
        ("'The Road Not Taken' was written by:",
         ["Robert Frost", "Wordsworth", "Tagore", "Shelley"], 0, 0.0),
        ("'Wind' (Beehive) is a poem by:",
         ["Subramania Bharati", "Rabindranath Tagore", "Sarojini Naidu", "Tennyson"], 0, 0.5),
        ("'No Men Are Foreign' communicates the theme of:",
         ["War's glory", "Universal brotherhood and rejection of war", "Patriotism only", "Travel"], 1, 0.5),
        ("'The Lake Isle of Innisfree' was written by:",
         ["W.B. Yeats", "T.S. Eliot", "Walt Whitman", "Frost"], 0, 0.5),
        ("Rhyme scheme 'AABB' means:",
         ["Two pairs of rhyming lines (couplets)", "Alternate rhyme", "No rhyme", "Triplet"], 0, 0.5),
    ],
    "C9E_MOM": [
        ("'The Lost Child' is by:",
         ["R.K. Narayan", "Mulk Raj Anand", "Tagore", "Premchand"], 1, 0.5),
        ("'Iswaran the Storyteller' is known for:",
         ["His business sense", "His vivid storytelling skill as a domestic helper", "His mountaineering", "His painting"], 1, 0.0),
        ("'In the Kingdom of Fools' shows that:",
         ["Wisdom always wins", "Foolish rulers can lead a kingdom into absurdity", "Money is everything", "Travel is dangerous"], 1, 0.5),
        ("'A House Is Not a Home' is about:",
         ["A new house being built", "A school fire and the rebuilding of a teenager's sense of belonging", "A ghost story", "A village fair"], 1, 0.5),
        ("'The Beggar' (Moments) is by:",
         ["Anton Chekhov", "Charles Dickens", "O. Henry", "Saki"], 0, 0.5),
    ],
    "C9E_GRAM": [
        ("Choose the correct modal: 'You ____ wear a helmet on a bike.'",
         ["might", "must", "could", "would"], 1, 0.0),
        ("Identify the clause type: 'When the bell rang, students left.' — 'When the bell rang' is a:",
         ["Main clause", "Subordinate (adverbial) clause", "Noun phrase", "Adjective"], 1, 0.5),
        ("Convert to passive: 'They built a school.' →",
         ["A school was built by them", "A school is built by them", "They were built a school", "A school built they"], 0, 0.5),
        ("Choose correct conjunction: 'I waited ____ he arrived.'",
         ["until", "unless", "although", "since"], 0, 0.0),
        ("A formal letter typically begins with:",
         ["'Hi'", "'Dear Sir/Madam'", "'Hey'", "'Yo'"], 1, -0.5),
    ],
    "C9E_READ": [
        ("In comprehension, 'tone' of a passage refers to:",
         ["Loudness", "Author's attitude towards the subject", "Word count", "Spelling"], 1, 0.5),
        ("Synonym is a word that:",
         ["Has the opposite meaning", "Has nearly the same meaning", "Sounds similar but means different", "Has no meaning"], 1, -0.5),
        ("Antonym of 'optimistic' is:",
         ["Hopeful", "Pessimistic", "Realistic", "Rational"], 1, 0.0),
        ("In a comprehension test, a 'detail' question asks for:",
         ["Personal opinion", "Specific information stated in the text", "An imaginative ending", "Translation"], 1, 0.0),
        ("Note-making demands that the reader:",
         ["Copy entire passages", "Identify key ideas and arrange them with headings", "Translate word-for-word", "Summarise into one word"], 1, 0.5),
    ],
}
